// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Nova configuração do Supabase
const SUPABASE_URL = 'https://wtwxggubulpikvsdiusn.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0d3hnZ3VidWxwaWt2c2RpdXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzU1NjcsImV4cCI6MjA3NzE1MTU2N30.xOkQBweMxpdGPI1UBtz4VP0OOoIfU7W5UOWzK743CEI';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'implicit'
  }
});